/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `SkillOnProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";

import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model SkillOnProfile
 *
 */
export type SkillOnProfileModel =
    runtime.Types.Result.DefaultSelection<Prisma.$SkillOnProfilePayload>;

export type AggregateSkillOnProfile = {
    _count: SkillOnProfileCountAggregateOutputType | null;
    _avg: SkillOnProfileAvgAggregateOutputType | null;
    _sum: SkillOnProfileSumAggregateOutputType | null;
    _min: SkillOnProfileMinAggregateOutputType | null;
    _max: SkillOnProfileMaxAggregateOutputType | null;
};

export type SkillOnProfileAvgAggregateOutputType = {
    profileId: number | null;
    skillId: number | null;
};

export type SkillOnProfileSumAggregateOutputType = {
    profileId: number | null;
    skillId: number | null;
};

export type SkillOnProfileMinAggregateOutputType = {
    profileId: number | null;
    skillId: number | null;
};

export type SkillOnProfileMaxAggregateOutputType = {
    profileId: number | null;
    skillId: number | null;
};

export type SkillOnProfileCountAggregateOutputType = {
    profileId: number;
    skillId: number;
    _all: number;
};

export type SkillOnProfileAvgAggregateInputType = {
    profileId?: true;
    skillId?: true;
};

export type SkillOnProfileSumAggregateInputType = {
    profileId?: true;
    skillId?: true;
};

export type SkillOnProfileMinAggregateInputType = {
    profileId?: true;
    skillId?: true;
};

export type SkillOnProfileMaxAggregateInputType = {
    profileId?: true;
    skillId?: true;
};

export type SkillOnProfileCountAggregateInputType = {
    profileId?: true;
    skillId?: true;
    _all?: true;
};

export type SkillOnProfileAggregateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which SkillOnProfile to aggregate.
     */
    where?: Prisma.SkillOnProfileWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of SkillOnProfiles to fetch.
     */
    orderBy?:
        | Prisma.SkillOnProfileOrderByWithRelationInput
        | Prisma.SkillOnProfileOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.SkillOnProfileWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` SkillOnProfiles from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` SkillOnProfiles.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned SkillOnProfiles
     **/
    _count?: true | SkillOnProfileCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to average
     **/
    _avg?: SkillOnProfileAvgAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to sum
     **/
    _sum?: SkillOnProfileSumAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: SkillOnProfileMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: SkillOnProfileMaxAggregateInputType;
};

export type GetSkillOnProfileAggregateType<T extends SkillOnProfileAggregateArgs> = {
    [P in keyof T & keyof AggregateSkillOnProfile]: P extends "_count" | "count"
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateSkillOnProfile[P]>
        : Prisma.GetScalarType<T[P], AggregateSkillOnProfile[P]>;
};

export type SkillOnProfileGroupByArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.SkillOnProfileWhereInput;
    orderBy?:
        | Prisma.SkillOnProfileOrderByWithAggregationInput
        | Prisma.SkillOnProfileOrderByWithAggregationInput[];
    by: Prisma.SkillOnProfileScalarFieldEnum[] | Prisma.SkillOnProfileScalarFieldEnum;
    having?: Prisma.SkillOnProfileScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: SkillOnProfileCountAggregateInputType | true;
    _avg?: SkillOnProfileAvgAggregateInputType;
    _sum?: SkillOnProfileSumAggregateInputType;
    _min?: SkillOnProfileMinAggregateInputType;
    _max?: SkillOnProfileMaxAggregateInputType;
};

export type SkillOnProfileGroupByOutputType = {
    profileId: number;
    skillId: number;
    _count: SkillOnProfileCountAggregateOutputType | null;
    _avg: SkillOnProfileAvgAggregateOutputType | null;
    _sum: SkillOnProfileSumAggregateOutputType | null;
    _min: SkillOnProfileMinAggregateOutputType | null;
    _max: SkillOnProfileMaxAggregateOutputType | null;
};

export type GetSkillOnProfileGroupByPayload<T extends SkillOnProfileGroupByArgs> =
    Prisma.PrismaPromise<
        Array<
            Prisma.PickEnumerable<SkillOnProfileGroupByOutputType, T["by"]> & {
                [P in keyof T & keyof SkillOnProfileGroupByOutputType]: P extends "_count"
                    ? T[P] extends boolean
                        ? number
                        : Prisma.GetScalarType<T[P], SkillOnProfileGroupByOutputType[P]>
                    : Prisma.GetScalarType<T[P], SkillOnProfileGroupByOutputType[P]>;
            }
        >
    >;

export type SkillOnProfileWhereInput = {
    AND?: Prisma.SkillOnProfileWhereInput | Prisma.SkillOnProfileWhereInput[];
    OR?: Prisma.SkillOnProfileWhereInput[];
    NOT?: Prisma.SkillOnProfileWhereInput | Prisma.SkillOnProfileWhereInput[];
    profileId?: Prisma.IntFilter<"SkillOnProfile"> | number;
    skillId?: Prisma.IntFilter<"SkillOnProfile"> | number;
    profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>;
    skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>;
};

export type SkillOnProfileOrderByWithRelationInput = {
    profileId?: Prisma.SortOrder;
    skillId?: Prisma.SortOrder;
    profile?: Prisma.ProfileOrderByWithRelationInput;
    skill?: Prisma.SkillOrderByWithRelationInput;
};

export type SkillOnProfileWhereUniqueInput = Prisma.AtLeast<
    {
        profileId_skillId?: Prisma.SkillOnProfileProfileIdSkillIdCompoundUniqueInput;
        AND?: Prisma.SkillOnProfileWhereInput | Prisma.SkillOnProfileWhereInput[];
        OR?: Prisma.SkillOnProfileWhereInput[];
        NOT?: Prisma.SkillOnProfileWhereInput | Prisma.SkillOnProfileWhereInput[];
        profileId?: Prisma.IntFilter<"SkillOnProfile"> | number;
        skillId?: Prisma.IntFilter<"SkillOnProfile"> | number;
        profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>;
        skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>;
    },
    "profileId_skillId"
>;

export type SkillOnProfileOrderByWithAggregationInput = {
    profileId?: Prisma.SortOrder;
    skillId?: Prisma.SortOrder;
    _count?: Prisma.SkillOnProfileCountOrderByAggregateInput;
    _avg?: Prisma.SkillOnProfileAvgOrderByAggregateInput;
    _max?: Prisma.SkillOnProfileMaxOrderByAggregateInput;
    _min?: Prisma.SkillOnProfileMinOrderByAggregateInput;
    _sum?: Prisma.SkillOnProfileSumOrderByAggregateInput;
};

export type SkillOnProfileScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.SkillOnProfileScalarWhereWithAggregatesInput
        | Prisma.SkillOnProfileScalarWhereWithAggregatesInput[];
    OR?: Prisma.SkillOnProfileScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.SkillOnProfileScalarWhereWithAggregatesInput
        | Prisma.SkillOnProfileScalarWhereWithAggregatesInput[];
    profileId?: Prisma.IntWithAggregatesFilter<"SkillOnProfile"> | number;
    skillId?: Prisma.IntWithAggregatesFilter<"SkillOnProfile"> | number;
};

export type SkillOnProfileCreateInput = {
    profile: Prisma.ProfileCreateNestedOneWithoutSkillsOnProfilesInput;
    skill: Prisma.SkillCreateNestedOneWithoutSkillsOnProfilesInput;
};

export type SkillOnProfileUncheckedCreateInput = {
    profileId: number;
    skillId: number;
};

export type SkillOnProfileUpdateInput = {
    profile?: Prisma.ProfileUpdateOneRequiredWithoutSkillsOnProfilesNestedInput;
    skill?: Prisma.SkillUpdateOneRequiredWithoutSkillsOnProfilesNestedInput;
};

export type SkillOnProfileUncheckedUpdateInput = {
    profileId?: Prisma.IntFieldUpdateOperationsInput | number;
    skillId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type SkillOnProfileCreateManyInput = {
    profileId: number;
    skillId: number;
};

export type SkillOnProfileUpdateManyMutationInput = {};

export type SkillOnProfileUncheckedUpdateManyInput = {
    profileId?: Prisma.IntFieldUpdateOperationsInput | number;
    skillId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type SkillOnProfileListRelationFilter = {
    every?: Prisma.SkillOnProfileWhereInput;
    some?: Prisma.SkillOnProfileWhereInput;
    none?: Prisma.SkillOnProfileWhereInput;
};

export type SkillOnProfileOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type SkillOnProfileProfileIdSkillIdCompoundUniqueInput = {
    profileId: number;
    skillId: number;
};

export type SkillOnProfileCountOrderByAggregateInput = {
    profileId?: Prisma.SortOrder;
    skillId?: Prisma.SortOrder;
};

export type SkillOnProfileAvgOrderByAggregateInput = {
    profileId?: Prisma.SortOrder;
    skillId?: Prisma.SortOrder;
};

export type SkillOnProfileMaxOrderByAggregateInput = {
    profileId?: Prisma.SortOrder;
    skillId?: Prisma.SortOrder;
};

export type SkillOnProfileMinOrderByAggregateInput = {
    profileId?: Prisma.SortOrder;
    skillId?: Prisma.SortOrder;
};

export type SkillOnProfileSumOrderByAggregateInput = {
    profileId?: Prisma.SortOrder;
    skillId?: Prisma.SortOrder;
};

export type SkillOnProfileCreateNestedManyWithoutProfileInput = {
    create?:
        | Prisma.XOR<
              Prisma.SkillOnProfileCreateWithoutProfileInput,
              Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput
          >
        | Prisma.SkillOnProfileCreateWithoutProfileInput[]
        | Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput[];
    connectOrCreate?:
        | Prisma.SkillOnProfileCreateOrConnectWithoutProfileInput
        | Prisma.SkillOnProfileCreateOrConnectWithoutProfileInput[];
    createMany?: Prisma.SkillOnProfileCreateManyProfileInputEnvelope;
    connect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
};

export type SkillOnProfileUncheckedCreateNestedManyWithoutProfileInput = {
    create?:
        | Prisma.XOR<
              Prisma.SkillOnProfileCreateWithoutProfileInput,
              Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput
          >
        | Prisma.SkillOnProfileCreateWithoutProfileInput[]
        | Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput[];
    connectOrCreate?:
        | Prisma.SkillOnProfileCreateOrConnectWithoutProfileInput
        | Prisma.SkillOnProfileCreateOrConnectWithoutProfileInput[];
    createMany?: Prisma.SkillOnProfileCreateManyProfileInputEnvelope;
    connect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
};

export type SkillOnProfileUpdateManyWithoutProfileNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.SkillOnProfileCreateWithoutProfileInput,
              Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput
          >
        | Prisma.SkillOnProfileCreateWithoutProfileInput[]
        | Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput[];
    connectOrCreate?:
        | Prisma.SkillOnProfileCreateOrConnectWithoutProfileInput
        | Prisma.SkillOnProfileCreateOrConnectWithoutProfileInput[];
    upsert?:
        | Prisma.SkillOnProfileUpsertWithWhereUniqueWithoutProfileInput
        | Prisma.SkillOnProfileUpsertWithWhereUniqueWithoutProfileInput[];
    createMany?: Prisma.SkillOnProfileCreateManyProfileInputEnvelope;
    set?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    disconnect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    delete?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    connect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    update?:
        | Prisma.SkillOnProfileUpdateWithWhereUniqueWithoutProfileInput
        | Prisma.SkillOnProfileUpdateWithWhereUniqueWithoutProfileInput[];
    updateMany?:
        | Prisma.SkillOnProfileUpdateManyWithWhereWithoutProfileInput
        | Prisma.SkillOnProfileUpdateManyWithWhereWithoutProfileInput[];
    deleteMany?: Prisma.SkillOnProfileScalarWhereInput | Prisma.SkillOnProfileScalarWhereInput[];
};

export type SkillOnProfileUncheckedUpdateManyWithoutProfileNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.SkillOnProfileCreateWithoutProfileInput,
              Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput
          >
        | Prisma.SkillOnProfileCreateWithoutProfileInput[]
        | Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput[];
    connectOrCreate?:
        | Prisma.SkillOnProfileCreateOrConnectWithoutProfileInput
        | Prisma.SkillOnProfileCreateOrConnectWithoutProfileInput[];
    upsert?:
        | Prisma.SkillOnProfileUpsertWithWhereUniqueWithoutProfileInput
        | Prisma.SkillOnProfileUpsertWithWhereUniqueWithoutProfileInput[];
    createMany?: Prisma.SkillOnProfileCreateManyProfileInputEnvelope;
    set?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    disconnect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    delete?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    connect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    update?:
        | Prisma.SkillOnProfileUpdateWithWhereUniqueWithoutProfileInput
        | Prisma.SkillOnProfileUpdateWithWhereUniqueWithoutProfileInput[];
    updateMany?:
        | Prisma.SkillOnProfileUpdateManyWithWhereWithoutProfileInput
        | Prisma.SkillOnProfileUpdateManyWithWhereWithoutProfileInput[];
    deleteMany?: Prisma.SkillOnProfileScalarWhereInput | Prisma.SkillOnProfileScalarWhereInput[];
};

export type SkillOnProfileCreateNestedManyWithoutSkillInput = {
    create?:
        | Prisma.XOR<
              Prisma.SkillOnProfileCreateWithoutSkillInput,
              Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput
          >
        | Prisma.SkillOnProfileCreateWithoutSkillInput[]
        | Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput[];
    connectOrCreate?:
        | Prisma.SkillOnProfileCreateOrConnectWithoutSkillInput
        | Prisma.SkillOnProfileCreateOrConnectWithoutSkillInput[];
    createMany?: Prisma.SkillOnProfileCreateManySkillInputEnvelope;
    connect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
};

export type SkillOnProfileUncheckedCreateNestedManyWithoutSkillInput = {
    create?:
        | Prisma.XOR<
              Prisma.SkillOnProfileCreateWithoutSkillInput,
              Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput
          >
        | Prisma.SkillOnProfileCreateWithoutSkillInput[]
        | Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput[];
    connectOrCreate?:
        | Prisma.SkillOnProfileCreateOrConnectWithoutSkillInput
        | Prisma.SkillOnProfileCreateOrConnectWithoutSkillInput[];
    createMany?: Prisma.SkillOnProfileCreateManySkillInputEnvelope;
    connect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
};

export type SkillOnProfileUpdateManyWithoutSkillNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.SkillOnProfileCreateWithoutSkillInput,
              Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput
          >
        | Prisma.SkillOnProfileCreateWithoutSkillInput[]
        | Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput[];
    connectOrCreate?:
        | Prisma.SkillOnProfileCreateOrConnectWithoutSkillInput
        | Prisma.SkillOnProfileCreateOrConnectWithoutSkillInput[];
    upsert?:
        | Prisma.SkillOnProfileUpsertWithWhereUniqueWithoutSkillInput
        | Prisma.SkillOnProfileUpsertWithWhereUniqueWithoutSkillInput[];
    createMany?: Prisma.SkillOnProfileCreateManySkillInputEnvelope;
    set?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    disconnect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    delete?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    connect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    update?:
        | Prisma.SkillOnProfileUpdateWithWhereUniqueWithoutSkillInput
        | Prisma.SkillOnProfileUpdateWithWhereUniqueWithoutSkillInput[];
    updateMany?:
        | Prisma.SkillOnProfileUpdateManyWithWhereWithoutSkillInput
        | Prisma.SkillOnProfileUpdateManyWithWhereWithoutSkillInput[];
    deleteMany?: Prisma.SkillOnProfileScalarWhereInput | Prisma.SkillOnProfileScalarWhereInput[];
};

export type SkillOnProfileUncheckedUpdateManyWithoutSkillNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.SkillOnProfileCreateWithoutSkillInput,
              Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput
          >
        | Prisma.SkillOnProfileCreateWithoutSkillInput[]
        | Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput[];
    connectOrCreate?:
        | Prisma.SkillOnProfileCreateOrConnectWithoutSkillInput
        | Prisma.SkillOnProfileCreateOrConnectWithoutSkillInput[];
    upsert?:
        | Prisma.SkillOnProfileUpsertWithWhereUniqueWithoutSkillInput
        | Prisma.SkillOnProfileUpsertWithWhereUniqueWithoutSkillInput[];
    createMany?: Prisma.SkillOnProfileCreateManySkillInputEnvelope;
    set?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    disconnect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    delete?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    connect?: Prisma.SkillOnProfileWhereUniqueInput | Prisma.SkillOnProfileWhereUniqueInput[];
    update?:
        | Prisma.SkillOnProfileUpdateWithWhereUniqueWithoutSkillInput
        | Prisma.SkillOnProfileUpdateWithWhereUniqueWithoutSkillInput[];
    updateMany?:
        | Prisma.SkillOnProfileUpdateManyWithWhereWithoutSkillInput
        | Prisma.SkillOnProfileUpdateManyWithWhereWithoutSkillInput[];
    deleteMany?: Prisma.SkillOnProfileScalarWhereInput | Prisma.SkillOnProfileScalarWhereInput[];
};

export type SkillOnProfileCreateWithoutProfileInput = {
    skill: Prisma.SkillCreateNestedOneWithoutSkillsOnProfilesInput;
};

export type SkillOnProfileUncheckedCreateWithoutProfileInput = {
    skillId: number;
};

export type SkillOnProfileCreateOrConnectWithoutProfileInput = {
    where: Prisma.SkillOnProfileWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.SkillOnProfileCreateWithoutProfileInput,
        Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput
    >;
};

export type SkillOnProfileCreateManyProfileInputEnvelope = {
    data:
        | Prisma.SkillOnProfileCreateManyProfileInput
        | Prisma.SkillOnProfileCreateManyProfileInput[];
    skipDuplicates?: boolean;
};

export type SkillOnProfileUpsertWithWhereUniqueWithoutProfileInput = {
    where: Prisma.SkillOnProfileWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.SkillOnProfileUpdateWithoutProfileInput,
        Prisma.SkillOnProfileUncheckedUpdateWithoutProfileInput
    >;
    create: Prisma.XOR<
        Prisma.SkillOnProfileCreateWithoutProfileInput,
        Prisma.SkillOnProfileUncheckedCreateWithoutProfileInput
    >;
};

export type SkillOnProfileUpdateWithWhereUniqueWithoutProfileInput = {
    where: Prisma.SkillOnProfileWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.SkillOnProfileUpdateWithoutProfileInput,
        Prisma.SkillOnProfileUncheckedUpdateWithoutProfileInput
    >;
};

export type SkillOnProfileUpdateManyWithWhereWithoutProfileInput = {
    where: Prisma.SkillOnProfileScalarWhereInput;
    data: Prisma.XOR<
        Prisma.SkillOnProfileUpdateManyMutationInput,
        Prisma.SkillOnProfileUncheckedUpdateManyWithoutProfileInput
    >;
};

export type SkillOnProfileScalarWhereInput = {
    AND?: Prisma.SkillOnProfileScalarWhereInput | Prisma.SkillOnProfileScalarWhereInput[];
    OR?: Prisma.SkillOnProfileScalarWhereInput[];
    NOT?: Prisma.SkillOnProfileScalarWhereInput | Prisma.SkillOnProfileScalarWhereInput[];
    profileId?: Prisma.IntFilter<"SkillOnProfile"> | number;
    skillId?: Prisma.IntFilter<"SkillOnProfile"> | number;
};

export type SkillOnProfileCreateWithoutSkillInput = {
    profile: Prisma.ProfileCreateNestedOneWithoutSkillsOnProfilesInput;
};

export type SkillOnProfileUncheckedCreateWithoutSkillInput = {
    profileId: number;
};

export type SkillOnProfileCreateOrConnectWithoutSkillInput = {
    where: Prisma.SkillOnProfileWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.SkillOnProfileCreateWithoutSkillInput,
        Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput
    >;
};

export type SkillOnProfileCreateManySkillInputEnvelope = {
    data: Prisma.SkillOnProfileCreateManySkillInput | Prisma.SkillOnProfileCreateManySkillInput[];
    skipDuplicates?: boolean;
};

export type SkillOnProfileUpsertWithWhereUniqueWithoutSkillInput = {
    where: Prisma.SkillOnProfileWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.SkillOnProfileUpdateWithoutSkillInput,
        Prisma.SkillOnProfileUncheckedUpdateWithoutSkillInput
    >;
    create: Prisma.XOR<
        Prisma.SkillOnProfileCreateWithoutSkillInput,
        Prisma.SkillOnProfileUncheckedCreateWithoutSkillInput
    >;
};

export type SkillOnProfileUpdateWithWhereUniqueWithoutSkillInput = {
    where: Prisma.SkillOnProfileWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.SkillOnProfileUpdateWithoutSkillInput,
        Prisma.SkillOnProfileUncheckedUpdateWithoutSkillInput
    >;
};

export type SkillOnProfileUpdateManyWithWhereWithoutSkillInput = {
    where: Prisma.SkillOnProfileScalarWhereInput;
    data: Prisma.XOR<
        Prisma.SkillOnProfileUpdateManyMutationInput,
        Prisma.SkillOnProfileUncheckedUpdateManyWithoutSkillInput
    >;
};

export type SkillOnProfileCreateManyProfileInput = {
    skillId: number;
};

export type SkillOnProfileUpdateWithoutProfileInput = {
    skill?: Prisma.SkillUpdateOneRequiredWithoutSkillsOnProfilesNestedInput;
};

export type SkillOnProfileUncheckedUpdateWithoutProfileInput = {
    skillId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type SkillOnProfileUncheckedUpdateManyWithoutProfileInput = {
    skillId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type SkillOnProfileCreateManySkillInput = {
    profileId: number;
};

export type SkillOnProfileUpdateWithoutSkillInput = {
    profile?: Prisma.ProfileUpdateOneRequiredWithoutSkillsOnProfilesNestedInput;
};

export type SkillOnProfileUncheckedUpdateWithoutSkillInput = {
    profileId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type SkillOnProfileUncheckedUpdateManyWithoutSkillInput = {
    profileId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type SkillOnProfileSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        profileId?: boolean;
        skillId?: boolean;
        profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
        skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["skillOnProfile"]
>;

export type SkillOnProfileSelectCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        profileId?: boolean;
        skillId?: boolean;
        profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
        skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["skillOnProfile"]
>;

export type SkillOnProfileSelectUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        profileId?: boolean;
        skillId?: boolean;
        profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
        skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["skillOnProfile"]
>;

export type SkillOnProfileSelectScalar = {
    profileId?: boolean;
    skillId?: boolean;
};

export type SkillOnProfileOmit<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<"profileId" | "skillId", ExtArgs["result"]["skillOnProfile"]>;
export type SkillOnProfileInclude<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
    skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>;
};
export type SkillOnProfileIncludeCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
    skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>;
};
export type SkillOnProfileIncludeUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>;
    skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>;
};

export type $SkillOnProfilePayload<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    name: "SkillOnProfile";
    objects: {
        profile: Prisma.$ProfilePayload<ExtArgs>;
        skill: Prisma.$SkillPayload<ExtArgs>;
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            profileId: number;
            skillId: number;
        },
        ExtArgs["result"]["skillOnProfile"]
    >;
    composites: {};
};

export type SkillOnProfileGetPayload<
    S extends boolean | null | undefined | SkillOnProfileDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$SkillOnProfilePayload, S>;

export type SkillOnProfileCountArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<SkillOnProfileFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
    select?: SkillOnProfileCountAggregateInputType | true;
};

export interface SkillOnProfileDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>["model"]["SkillOnProfile"];
        meta: { name: "SkillOnProfile" };
    };
    /**
     * Find zero or one SkillOnProfile that matches the filter.
     * @param {SkillOnProfileFindUniqueArgs} args - Arguments to find a SkillOnProfile
     * @example
     * // Get one SkillOnProfile
     * const skillOnProfile = await prisma.skillOnProfile.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends SkillOnProfileFindUniqueArgs>(
        args: Prisma.SelectSubset<T, SkillOnProfileFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__SkillOnProfileClient<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "findUnique",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one SkillOnProfile that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {SkillOnProfileFindUniqueOrThrowArgs} args - Arguments to find a SkillOnProfile
     * @example
     * // Get one SkillOnProfile
     * const skillOnProfile = await prisma.skillOnProfile.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends SkillOnProfileFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<T, SkillOnProfileFindUniqueOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__SkillOnProfileClient<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "findUniqueOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first SkillOnProfile that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {SkillOnProfileFindFirstArgs} args - Arguments to find a SkillOnProfile
     * @example
     * // Get one SkillOnProfile
     * const skillOnProfile = await prisma.skillOnProfile.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends SkillOnProfileFindFirstArgs>(
        args?: Prisma.SelectSubset<T, SkillOnProfileFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__SkillOnProfileClient<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "findFirst",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first SkillOnProfile that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {SkillOnProfileFindFirstOrThrowArgs} args - Arguments to find a SkillOnProfile
     * @example
     * // Get one SkillOnProfile
     * const skillOnProfile = await prisma.skillOnProfile.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends SkillOnProfileFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<T, SkillOnProfileFindFirstOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__SkillOnProfileClient<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "findFirstOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more SkillOnProfiles that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {SkillOnProfileFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all SkillOnProfiles
     * const skillOnProfiles = await prisma.skillOnProfile.findMany()
     *
     * // Get first 10 SkillOnProfiles
     * const skillOnProfiles = await prisma.skillOnProfile.findMany({ take: 10 })
     *
     * // Only select the `profileId`
     * const skillOnProfileWithProfileIdOnly = await prisma.skillOnProfile.findMany({ select: { profileId: true } })
     *
     */
    findMany<T extends SkillOnProfileFindManyArgs>(
        args?: Prisma.SelectSubset<T, SkillOnProfileFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "findMany",
            GlobalOmitOptions
        >
    >;

    /**
     * Create a SkillOnProfile.
     * @param {SkillOnProfileCreateArgs} args - Arguments to create a SkillOnProfile.
     * @example
     * // Create one SkillOnProfile
     * const SkillOnProfile = await prisma.skillOnProfile.create({
     *   data: {
     *     // ... data to create a SkillOnProfile
     *   }
     * })
     *
     */
    create<T extends SkillOnProfileCreateArgs>(
        args: Prisma.SelectSubset<T, SkillOnProfileCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__SkillOnProfileClient<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "create",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many SkillOnProfiles.
     * @param {SkillOnProfileCreateManyArgs} args - Arguments to create many SkillOnProfiles.
     * @example
     * // Create many SkillOnProfiles
     * const skillOnProfile = await prisma.skillOnProfile.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends SkillOnProfileCreateManyArgs>(
        args?: Prisma.SelectSubset<T, SkillOnProfileCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many SkillOnProfiles and returns the data saved in the database.
     * @param {SkillOnProfileCreateManyAndReturnArgs} args - Arguments to create many SkillOnProfiles.
     * @example
     * // Create many SkillOnProfiles
     * const skillOnProfile = await prisma.skillOnProfile.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many SkillOnProfiles and only return the `profileId`
     * const skillOnProfileWithProfileIdOnly = await prisma.skillOnProfile.createManyAndReturn({
     *   select: { profileId: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends SkillOnProfileCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<T, SkillOnProfileCreateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "createManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a SkillOnProfile.
     * @param {SkillOnProfileDeleteArgs} args - Arguments to delete one SkillOnProfile.
     * @example
     * // Delete one SkillOnProfile
     * const SkillOnProfile = await prisma.skillOnProfile.delete({
     *   where: {
     *     // ... filter to delete one SkillOnProfile
     *   }
     * })
     *
     */
    delete<T extends SkillOnProfileDeleteArgs>(
        args: Prisma.SelectSubset<T, SkillOnProfileDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__SkillOnProfileClient<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "delete",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one SkillOnProfile.
     * @param {SkillOnProfileUpdateArgs} args - Arguments to update one SkillOnProfile.
     * @example
     * // Update one SkillOnProfile
     * const skillOnProfile = await prisma.skillOnProfile.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends SkillOnProfileUpdateArgs>(
        args: Prisma.SelectSubset<T, SkillOnProfileUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__SkillOnProfileClient<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "update",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more SkillOnProfiles.
     * @param {SkillOnProfileDeleteManyArgs} args - Arguments to filter SkillOnProfiles to delete.
     * @example
     * // Delete a few SkillOnProfiles
     * const { count } = await prisma.skillOnProfile.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends SkillOnProfileDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, SkillOnProfileDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more SkillOnProfiles.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {SkillOnProfileUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many SkillOnProfiles
     * const skillOnProfile = await prisma.skillOnProfile.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends SkillOnProfileUpdateManyArgs>(
        args: Prisma.SelectSubset<T, SkillOnProfileUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more SkillOnProfiles and returns the data updated in the database.
     * @param {SkillOnProfileUpdateManyAndReturnArgs} args - Arguments to update many SkillOnProfiles.
     * @example
     * // Update many SkillOnProfiles
     * const skillOnProfile = await prisma.skillOnProfile.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more SkillOnProfiles and only return the `profileId`
     * const skillOnProfileWithProfileIdOnly = await prisma.skillOnProfile.updateManyAndReturn({
     *   select: { profileId: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends SkillOnProfileUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<T, SkillOnProfileUpdateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "updateManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one SkillOnProfile.
     * @param {SkillOnProfileUpsertArgs} args - Arguments to update or create a SkillOnProfile.
     * @example
     * // Update or create a SkillOnProfile
     * const skillOnProfile = await prisma.skillOnProfile.upsert({
     *   create: {
     *     // ... data to create a SkillOnProfile
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the SkillOnProfile we want to update
     *   }
     * })
     */
    upsert<T extends SkillOnProfileUpsertArgs>(
        args: Prisma.SelectSubset<T, SkillOnProfileUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__SkillOnProfileClient<
        runtime.Types.Result.GetResult<
            Prisma.$SkillOnProfilePayload<ExtArgs>,
            T,
            "upsert",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of SkillOnProfiles.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {SkillOnProfileCountArgs} args - Arguments to filter SkillOnProfiles to count.
     * @example
     * // Count the number of SkillOnProfiles
     * const count = await prisma.skillOnProfile.count({
     *   where: {
     *     // ... the filter for the SkillOnProfiles we want to count
     *   }
     * })
     **/
    count<T extends SkillOnProfileCountArgs>(
        args?: Prisma.Subset<T, SkillOnProfileCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<"select", any>
            ? T["select"] extends true
                ? number
                : Prisma.GetScalarType<T["select"], SkillOnProfileCountAggregateOutputType>
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a SkillOnProfile.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {SkillOnProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends SkillOnProfileAggregateArgs>(
        args: Prisma.Subset<T, SkillOnProfileAggregateArgs>,
    ): Prisma.PrismaPromise<GetSkillOnProfileAggregateType<T>>;

    /**
     * Group by SkillOnProfile.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {SkillOnProfileGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends SkillOnProfileGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<"skip", Prisma.Keys<T>>,
            Prisma.Extends<"take", Prisma.Keys<T>>
        >,
        OrderByArg extends (Prisma.True extends HasSelectOrTake
            ? { orderBy: SkillOnProfileGroupByArgs["orderBy"] }
            : { orderBy?: SkillOnProfileGroupByArgs["orderBy"] }),
        OrderFields extends Prisma.ExcludeUnderscoreKeys<
            Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
        >,
        ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T["having"]>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends (T["by"] extends never[] ? Prisma.True : Prisma.False),
        InputErrors extends (ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
                }[HavingFields]
              : "take" extends Prisma.Keys<T>
                ? "orderBy" extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : "skip" extends Prisma.Keys<T>
                  ? "orderBy" extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields]),
    >(
        args: Prisma.SubsetIntersection<T, SkillOnProfileGroupByArgs, OrderByArg> & InputErrors,
    ): {} extends InputErrors
        ? GetSkillOnProfileGroupByPayload<T>
        : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the SkillOnProfile model
     */
    readonly fields: SkillOnProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SkillOnProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SkillOnProfileClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    profile<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__ProfileClient<
        | runtime.Types.Result.GetResult<
              Prisma.$ProfilePayload<ExtArgs>,
              T,
              "findUniqueOrThrow",
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    skill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__SkillClient<
        | runtime.Types.Result.GetResult<
              Prisma.$SkillPayload<ExtArgs>,
              T,
              "findUniqueOrThrow",
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
        onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the SkillOnProfile model
 */
export interface SkillOnProfileFieldRefs {
    readonly profileId: Prisma.FieldRef<"SkillOnProfile", "Int">;
    readonly skillId: Prisma.FieldRef<"SkillOnProfile", "Int">;
}

// Custom InputTypes
/**
 * SkillOnProfile findUnique
 */
export type SkillOnProfileFindUniqueArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
    /**
     * Filter, which SkillOnProfile to fetch.
     */
    where: Prisma.SkillOnProfileWhereUniqueInput;
};

/**
 * SkillOnProfile findUniqueOrThrow
 */
export type SkillOnProfileFindUniqueOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
    /**
     * Filter, which SkillOnProfile to fetch.
     */
    where: Prisma.SkillOnProfileWhereUniqueInput;
};

/**
 * SkillOnProfile findFirst
 */
export type SkillOnProfileFindFirstArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
    /**
     * Filter, which SkillOnProfile to fetch.
     */
    where?: Prisma.SkillOnProfileWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of SkillOnProfiles to fetch.
     */
    orderBy?:
        | Prisma.SkillOnProfileOrderByWithRelationInput
        | Prisma.SkillOnProfileOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for SkillOnProfiles.
     */
    cursor?: Prisma.SkillOnProfileWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` SkillOnProfiles from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` SkillOnProfiles.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of SkillOnProfiles.
     */
    distinct?: Prisma.SkillOnProfileScalarFieldEnum | Prisma.SkillOnProfileScalarFieldEnum[];
};

/**
 * SkillOnProfile findFirstOrThrow
 */
export type SkillOnProfileFindFirstOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
    /**
     * Filter, which SkillOnProfile to fetch.
     */
    where?: Prisma.SkillOnProfileWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of SkillOnProfiles to fetch.
     */
    orderBy?:
        | Prisma.SkillOnProfileOrderByWithRelationInput
        | Prisma.SkillOnProfileOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for SkillOnProfiles.
     */
    cursor?: Prisma.SkillOnProfileWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` SkillOnProfiles from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` SkillOnProfiles.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of SkillOnProfiles.
     */
    distinct?: Prisma.SkillOnProfileScalarFieldEnum | Prisma.SkillOnProfileScalarFieldEnum[];
};

/**
 * SkillOnProfile findMany
 */
export type SkillOnProfileFindManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
    /**
     * Filter, which SkillOnProfiles to fetch.
     */
    where?: Prisma.SkillOnProfileWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of SkillOnProfiles to fetch.
     */
    orderBy?:
        | Prisma.SkillOnProfileOrderByWithRelationInput
        | Prisma.SkillOnProfileOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing SkillOnProfiles.
     */
    cursor?: Prisma.SkillOnProfileWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` SkillOnProfiles from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` SkillOnProfiles.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of SkillOnProfiles.
     */
    distinct?: Prisma.SkillOnProfileScalarFieldEnum | Prisma.SkillOnProfileScalarFieldEnum[];
};

/**
 * SkillOnProfile create
 */
export type SkillOnProfileCreateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
    /**
     * The data needed to create a SkillOnProfile.
     */
    data: Prisma.XOR<Prisma.SkillOnProfileCreateInput, Prisma.SkillOnProfileUncheckedCreateInput>;
};

/**
 * SkillOnProfile createMany
 */
export type SkillOnProfileCreateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many SkillOnProfiles.
     */
    data: Prisma.SkillOnProfileCreateManyInput | Prisma.SkillOnProfileCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * SkillOnProfile createManyAndReturn
 */
export type SkillOnProfileCreateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * The data used to create many SkillOnProfiles.
     */
    data: Prisma.SkillOnProfileCreateManyInput | Prisma.SkillOnProfileCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * SkillOnProfile update
 */
export type SkillOnProfileUpdateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
    /**
     * The data needed to update a SkillOnProfile.
     */
    data: Prisma.XOR<Prisma.SkillOnProfileUpdateInput, Prisma.SkillOnProfileUncheckedUpdateInput>;
    /**
     * Choose, which SkillOnProfile to update.
     */
    where: Prisma.SkillOnProfileWhereUniqueInput;
};

/**
 * SkillOnProfile updateMany
 */
export type SkillOnProfileUpdateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update SkillOnProfiles.
     */
    data: Prisma.XOR<
        Prisma.SkillOnProfileUpdateManyMutationInput,
        Prisma.SkillOnProfileUncheckedUpdateManyInput
    >;
    /**
     * Filter which SkillOnProfiles to update
     */
    where?: Prisma.SkillOnProfileWhereInput;
    /**
     * Limit how many SkillOnProfiles to update.
     */
    limit?: number;
};

/**
 * SkillOnProfile updateManyAndReturn
 */
export type SkillOnProfileUpdateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * The data used to update SkillOnProfiles.
     */
    data: Prisma.XOR<
        Prisma.SkillOnProfileUpdateManyMutationInput,
        Prisma.SkillOnProfileUncheckedUpdateManyInput
    >;
    /**
     * Filter which SkillOnProfiles to update
     */
    where?: Prisma.SkillOnProfileWhereInput;
    /**
     * Limit how many SkillOnProfiles to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * SkillOnProfile upsert
 */
export type SkillOnProfileUpsertArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
    /**
     * The filter to search for the SkillOnProfile to update in case it exists.
     */
    where: Prisma.SkillOnProfileWhereUniqueInput;
    /**
     * In case the SkillOnProfile found by the `where` argument doesn't exist, create a new SkillOnProfile with this data.
     */
    create: Prisma.XOR<Prisma.SkillOnProfileCreateInput, Prisma.SkillOnProfileUncheckedCreateInput>;
    /**
     * In case the SkillOnProfile was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<Prisma.SkillOnProfileUpdateInput, Prisma.SkillOnProfileUncheckedUpdateInput>;
};

/**
 * SkillOnProfile delete
 */
export type SkillOnProfileDeleteArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
    /**
     * Filter which SkillOnProfile to delete.
     */
    where: Prisma.SkillOnProfileWhereUniqueInput;
};

/**
 * SkillOnProfile deleteMany
 */
export type SkillOnProfileDeleteManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which SkillOnProfiles to delete
     */
    where?: Prisma.SkillOnProfileWhereInput;
    /**
     * Limit how many SkillOnProfiles to delete.
     */
    limit?: number;
};

/**
 * SkillOnProfile without action
 */
export type SkillOnProfileDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the SkillOnProfile
     */
    select?: Prisma.SkillOnProfileSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the SkillOnProfile
     */
    omit?: Prisma.SkillOnProfileOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.SkillOnProfileInclude<ExtArgs> | null;
};
