/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from "./models/Profile";
export type * from "./models/UsefulLink";
export type * from "./models/Skill";
export type * from "./models/SkillOnProfile";
export type * from "./models/Company";
export type * from "./models/WorkExperience";
export type * from "./models/Project";
export type * from "./commonInputTypes";
